### ISSUE TITLE
Suggestion - Make percentage a whole number

### ISSUE THREAD

**Issue by SnowShock35** [SuperCoder7979/fabric-chunkpregenerator#2]
Hi there,

I couldn't find any information on this repo or on CF about whether or not feedback is welcome. So I apologise in advanced if it's not. 

I had a quick suggestion for the mod. Currently, the percentage displayed in chat shows the percentage to 10 or so decimal places. Perhaps rounding it to 1 or 0 decimal places would look nicer. Also, it's unlikely that a server admin and or player needs such precision.

**Comment by SuperCoder7979** [comment]
Yeah that's a good idea, I just haven't done it because of ~~laziness~~ being busy with other stuff. It'll be in the next release

**Comment by SnowShock35** [comment]
> Yeah that's a good idea, I just haven't done it because of ~laziness~ being busy with other stuff. It'll be in the next release.

😂 I know the feeling... Thanks though 😄

**Comment by SuperCoder7979** [comment]
fixed in 0.2.2, the percent is now limited to 2 decimal places :)
